######################################################################
#  Project
######################################################################

BINARY		= rtos-adc
SRCFILES	= main.c    
SRCFILES += libs/freertos/Source/portable/MemMang/heap_4.c 
SRCFILES += libs/freertos/Source/list.c 
SRCFILES += libs/freertos/Source/portable/GCC/ARM_CM3/port.c 
SRCFILES += libs/freertos/Source/tasks.c 
SRCFILES += libs/freertos/Source/queue.c

include ./Makefile.incl
include ./Makefile.rtos
# End