######################################################################
#  Project
######################################################################

BINARY		= rtos-template
SRCFILES	= main.c libs/freertos/src/heap_4.c libs/freertos/src/list.c libs/freertos/src/port.c libs/freertos/src/tasks.c libs/freertos/src/opencm3.c # libs/freertos/src/queue.c


include ./Makefile.incl
nclude ./Makefile.rtos
# End