######################################################################
#  Project
######################################################################

BINARY		= rtos-template
SRCFILES	= main.c libs/freertos/src/MemMang/heap_4.c libs/freertos/src/list.c libs/freertos/portable/GCC/ARM_CM3/port.c libs/freertos/src/tasks.c # libs/freertos/src/queue.c


include ./Makefile.incl
include ./Makefile.rtos
# End