######################################################################
#  Project
######################################################################

BINARY		= rtos-template
SRCFILES	= main.c 
SRCFILES += usbcdc.c
SRCFILES += adventure.c
SRCFILES += miniprintf.c
SRCFILES += getline.c
SRCFILES += libs/freertos/src/MemMang/heap_4.c 
SRCFILES += libs/freertos/src/list.c 
SRCFILES += libs/freertos/portable/GCC/ARM_CM3/port.c 
SRCFILES += libs/freertos/src/tasks.c 
SRCFILES += libs/freertos/src/queue.c


include ./Makefile.incl
include ./Makefile.rtos
# End