######################################################################
#  Project
######################################################################

BINARY		= miniblink
SRCFILES	= main.c
SRCFILES	+= stm32f1xx_hal_gpio.c
SRCFILES	+= stm32f1xx_hal_rcc.c

all: elf bin

include ./Makefile.incl

# End