PREFIX		?= arm-none-eabi

TOP_DIR 	:= $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
STM32_HAL_DIR 	:= $(abspath $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/hal/inc)
STM32_CMISS_CORE_DIR 	:= $(abspath $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/cmiss/Include)
STM32_CMISS_DIR 	:= $(abspath $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/cmiss/Device/ST/STM32F1xx/Include)

DEFS		+= -DSTM32F1

ARCH_FLAGS	= -mthumb -mcpu=cortex-m3
ASFLAGS		= -mthumb -mcpu=cortex-m3

CC		:= $(PREFIX)-gcc
LD		:= $(CC)
AS		:= $(PREFIX)-as
OBJCOPY		:= $(PREFIX)-objcopy
SIZE		:= $(PREFIX)-size
OBJDUMP		:= $(PREFIX)-objdump
STFLASH		= $(shell which st-flash)

OPT		:= -Os -g

TEMP1 		= $(patsubst %.c,%.o,$(SRCFILES))
TEMP2		= $(patsubst %.s,%.o,$(TEMP1))
OBJS 		= $(patsubst %.cpp,%.o,$(TEMP2))

LDSCRIPT	?= $(TOP_DIR)/F103C8.ld

TGT_CFLAGS	+= $(OPT)
TGT_CFLAGS	+= $(ARCH_FLAGS)
TGT_CFLAGS	+= -ffunction-sections -fdata-sections
TGT_CFLAGS	+= $(DEFS)

TGT_CFLAGS	+= -I$(STM32_CMISS_DIR)
TGT_CFLAGS	+= -I$(STM32_CMISS_CORE_DIR)
TGT_CFLAGS	+= -I$(STM32_HAL_DIR)


# todo undefined reference to `_init'
#TGT_LDFLAGS	+= --static -nostartfiles
TGT_LDFLAGS	+= -T$(LDSCRIPT)
TGT_LDFLAGS	+= $(ARCH_FLAGS)
#TGT_LDFLAGS	+= -Wl,-Map=$(*).map	# todo delete
TGT_LDFLAGS	+= -Wl,--gc-sections

LDLIBS		+= -specs=nosys.specs

.SUFFIXES:	.elf .bin .hex .srec .list .map .images
.SECONDEXPANSION:
.SECONDARY:

elf:	$(DEPS) $(BINARY).elf
bin:	$(DEPS) $(BINARY).bin
hex:	$(DEPS) $(BINARY).hex
srec:	$(DEPS) $(BINARY).srec
list:	$(DEPS) $(BINARY).list

# Define a helper macro for debugging make errors online
# you can type "make print-OPENCM3_DIR" and it will show you
# how that ended up being resolved by all of the included
# makefiles.
print-%:
	@echo $*=$($*)

%.images: %.bin %.hex %.srec %.list %.map
	@#printf "*** $* images generated ***\n"

%.bin: %.elf
	@#printf "  OBJCOPY $(*).bin\n"
	$(OBJCOPY) -Obinary $(*).elf $(*).bin

%.hex: %.elf
	@#printf "  OBJCOPY $(*).hex\n"
	$(OBJCOPY) -Oihex $(*).elf $(*).hex

%.srec: %.elf
	@#printf "  OBJCOPY $(*).srec\n"
	$(OBJCOPY) -Osrec $(*).elf $(*).srec

%.list: %.elf
	@#printf "  OBJDUMP $(*).list\n"
	$(OBJDUMP) -S $(*).elf > $(*).list

%.elf %.map: $(OBJS) $(LDSCRIPT)
	$(LD) $(TGT_LDFLAGS) $(LDFLAGS) $(OBJS) $(LDLIBS) -o $(*).elf
	$(SIZE) $(BINARY).elf

%.o: %.c
	@#printf "  CC      $(*).c\n"
	$(CC) $(TGT_CFLAGS) $(CFLAGS) -o $(*).o -c $(*).c

%.o: %.s
	$(AS) $(ASFLAGS) -o $*.o -c $<

clean:
	@#printf "  CLEAN\n"
	$(RM) *.o *.d *.bin *.elf *.map generated.* $(OBJS) $(patsubst %.o,%.d,$(OBJS))


clobber: clean
	rm -f *.elf *.bin *.hex *.srec *.list *.map $(CLOBBER)

# Flash 64k Device
flash:	$(BINARY).bin
	$(STFLASH) $(FLASHSIZE) write $(BINARY).bin 0x8000000

# Flash 128k Device
bigflash: $(BINARY).bin
	$(STFLASH) --flash=128k write $(BINARY).bin 0x8000000

.PHONY: images clean elf bin hex srec list all

-include $(OBJS:.o=.d)

# End