######################################################################
#  Project
######################################################################

BINARY		= miniblink
SRCFILES	= miniblink.c

#test:
#	@echo $(TOP_DIR)
#	@echo '$(OPENCM3_DIR)'	

all: elf bin

include Makefile.incl

# End