######################################################################
#  Project
######################################################################

BINARY		= rtos-template
SRCFILES	= main.c 
SRCFILES += getline.c 
SRCFILES += intelhex.c
SRCFILES += mcuio.c
SRCFILES += miniprintf.c
SRCFILES += uartlib.c
SRCFILES += usbcdc.c     
SRCFILES += libs/freertos/src/MemMang/heap_4.c 
SRCFILES += libs/freertos/src/list.c 
SRCFILES += libs/freertos/portable/GCC/ARM_CM3/port.c 
SRCFILES += libs/freertos/src/tasks.c 
SRCFILES += libs/freertos/src/queue.c


include ./Makefile.incl
include ./Makefile.rtos
# End